### ISSUE TITLE
List of things todo

### ISSUE THREAD

**Issue by alehuo** [alehuo/clubhouse-frontend#6]
- [ ] Enable strict checking for any
- [ ] Move model definitions to the shared package so the front-end can benefit from precisely typed models in API requests
- [ ] Convert remaining reducers to use *typesafe-actions* package
- [ ] Start using redux-observable
- [ ] Convert actions that use redux-thunk to observables
- [ ] Fix adding student union
- [ ] Fetch rules from the back-end
- [ ] Fetch session messages from the back-end
